version: "3.1"
services:
 springbootapp:
  environment:
  - MONGO_DB_HOSTNAME=mongo
  - MONGO_DB_USERNAME=qa
  - MONGO_DB_PASSWORD=qadb@123
 mongo:
  environment:
  - MONGO_INITDB_ROOT_USERNAME=qadb
  - MONGO_INITDB_ROOT_PASSWORD=qadb@123
